# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Scale Manager Instance API
  description: Trigger instance actions
  version: "1.0.0"
# the domain of the service
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /instance/{instanceIP}:
    put:
      summary: Instance actions
      description: |
        Endpoint for modifying instance parameters like ram, cpu and storage.
      parameters:
        - name: instanceIP
          in: path
          description: Instance IP to be resized
          required: true
          type: string
        - name: type
          in: query
          description: resize type.
          required: true
          type: string
          enum: ["abs", "rel", "percent"]
        - name: value
          in: query
          description: value.
          required: true
          type: string
        - name: component
          in: query
          description: Component to be resized.
          required: true
          type: string
          enum: ["cpu", "ram", "storage"]
      responses:
        200:
          description: Action successfully triggered
        406:
          description: Request could not be executed

